### ISSUE TITLE
Clunky error report

### ISSUE THREAD

**Issue by gabrielhdt** [tweag/smtlib-backends#43]
## Description
When the SMT solver returns an invalid answer, the program exits with `fd:5: Data.ByteString.hGetLine: end of file` which is not informative.

## Recipe
1. Create a simple cabal project with `smtlib-backends` and `smtlib-backends-process` as dependencies, and a single executable (let's name it `smtlib-test`).
3. Write an executable, in our case, the one indicated below, as `app/Main.hs` (or `exe/Main.hs` depending on cabal's configuration)
4. `nix shell nixpkgs#cabal-install nixpkgs#ghc nixpkgs#yices`
5. `cabal run`.

**Minimal example**
```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where
import qualified SMTLIB.Backends.Process as P
import qualified SMTLIB.Backends as SMT

main :: IO ()
main = do
    let cfg = P.Config { P.exe = "yices", P.args = [], P.reportError = const (return ()) }
    handle <- P.new cfg
    let backend = P.toBackend handle
    solver <- SMT.initSolver backend False
    output <- SMT.command solver "(get-info :name)"
    print output
```
_One should use the command `yices-smt2` for this example to succeed_.

## Wanted behaviour
A friendlier error message, such as `Invalid response from the solver`.

**Comment by facundominguez** [comment]
> A friendly error message, such as `Invalid response from the solver`

... and if possible the message should include the actual response from the solver. :thinking:

**Comment by qaristote** [comment]
I'll implement this but I'm actually a bit surprised that your example fails, `scanParen` should be able to read `yices`' error message:
```
stdin: syntax error: (line 1, column 2): get-info is not a command
```

**Comment by facundominguez** [comment]
Another thing that could improve the error message is to check on initialization of the backend that the binary is in the path with something like [findExecutable](https://hackage.haskell.org/package/directory-1.3.8.0/docs/System-Directory.html#v:findExecutable).

**Comment by qaristote** [comment]
> Another thing that could improve the error message is to check on initialization of the backend that the binary is in the path with something like [findExecutable](https://hackage.haskell.org/package/directory-1.3.8.0/docs/System-Directory.html#v:findExecutable).

I assume `typed-process` already deals with this and I consider the current error message sufficiently clear, so I'm closing this.
```
Exception: z3fdgfn: startProcess: posix_spawnp: does not exist ([smtlib-backends-process] while creating the solver process: No such file or directory)

```
