### ISSUE TITLE
`Backends`: expose `flushQueue`

### ISSUE THREAD

**Issue by qaristote** [tweag/smtlib-backends#48]
I see at least one use case for this: implementing `liquid-fixpoint`s `asyncCommand`. Currently the only way around this is to either disable queuing (an alternative could be to allow the disabling of queuing locally) or send dummy commands to force the queue to be sent to the solver.

**Comment by qaristote** [comment]
I don't think it's actually possible to do this at the level of the `Backends` module. The problem is basically the same as for sending an `(exit)` command: for the `Process` backend you only want to do a `write` operation but not try to read the response in `Queuing` mode or your program will hang. 

If we want this at the level of the `Backends` module we need to split the `send` method into a `read` and a `write` method, but then this would be awkward for the `Z3` backend reading and writing is done atomically.

So perhaps the better solution is just to allow enabling and disabling queuing, but in the case of liquid-fixpoint's `asyncCommand` this would mean constantly changing the solver's `:print-success` as well as recreating a queue, and that doesn't sound very efficient.
Another solution would be to add a `send_` method to the `Backend` datatype which would send a command without trying to read the solver's output.

**Comment by facundominguez** [comment]
> send dummy commands to force the queue to be sent to the solver

Suddenly, this looks more attractive. Which command could it be?

> Another solution would be to add a send_ method to the Backend datatype which would send a command without trying to read the solver's output.

This could be a reasonable solution too.

**Comment by qaristote** [comment]
> Suddenly, this looks more attractive. Which command could it be?

I don't really know, maybe `(get-info :something)`.
