### ISSUE TITLE
Missing model in solver response

### ISSUE THREAD

**Issue by bruderj15** [tweag/smtlib-backends#69]
**Describe the bug**
When using a solver via process in Queuing-Mode, giving it a satisfiable problem and sending `(get-model)`, `command` does only return `"sat"` and not the model.
When invoking the solver manually through CLI with the given .smt2, it responds with the model.

**To Reproduce**
Run below program with given .smt2 file.

```haskell
main :: IO ()
main = do
  input <- TIO.readFile "smt-mini.smt2"
  let myConfig = P.defaultConfig { P.exe = "cvc5", P.args = [] }
  P.with myConfig $ \handle -> do
    mysolver <- B.initSolver B.Queuing $ P.toBackend handle
    answer   <- B.command mysolver $ Data.ByteString.Builder.byteString $ Data.Text.Encoding.encodeUtf8 input

    print answer
```

smt-mini.smt2:
```smt2
(set-option :produce-models true)
(set-logic QF_LIA)

(declare-fun var_1 () Int)
(declare-fun var_2 () Int)

(assert (= var_1 var_2))

(check-sat)
(get-model)
(exit)
```

**Expected behavior**
Expected return-value of `command` to contain model.

**Environment**
 - OS name + version: Windows 11
 - Version of the code: 0.3

**Additional context**
Tested with CVC5 and MathSAT.

**Comment by facundominguez** [comment]
Hello @bruderj15. I don't think `command` and `command_` are intended to be called with multiple commands appended as in your example. One such call should be done for each command in your file.

The documentation of these functions could make this more explicit admittedly.

**Comment by bruderj15** [comment]
Thank you! I suggest adding such documentation soon.
