### ISSUE TITLE
Obtaining Solver that does not set default options

### ISSUE THREAD

**Issue by bruderj15** [tweag/smtlib-backends#70]
**Is your feature request related to a problem? Please describe.**
Using `initSolver` to get a `Solver` by default sets `(produce-models: true)` and `(print-success: true)` for `NoQueuing`.
This forces the user to handle success-responses and the model which he may not even use. 

**Describe the solution you'd like**
Do not set these flags by default.

**Describe alternatives you've considered**
Export the Solver constructor so the user does not have to rely on `initSolver`.

**Comment by facundominguez** [comment]
Hello @bruderj15. [The documentation](https://github.com/tweag/smtlib-backends/blob/b458ffd47bbc4aec55800d5104a0c08de0a4537d/src/SMTLIB/Backends.hs#L71-L79) discusses why `(print-success: true)` is set in that case. You are welcome to question the choice, but then we would need more of a justification to motivate the change.

> Export the Solver constructor so the user does not have to rely on initSolver.

Is it an alternative to turn `produce-models` off after the solver is created with a call to `command`?

TBH, I don't remember why `produce-models` is set in `initSolver`. Do you remember @qaristote?

**Comment by qaristote** [comment]
> TBH, I don't remember why `produce-models` is set in `initSolver`. Do you remember @qaristote?

IIRC it's because `produce-models` defaults to `false` in Z3 and setting it to `true` sounded like a more reasonable default when it came to interacting through an API, because a program making requests to a solver is gonna use the actual model -- Pirouette was doing so.

**Comment by facundominguez** [comment]
Thanks @qaristote! That's helpful context.
