### ISSUE TITLE
Up bounds for smtlib-backends to 0.4 in smtlib-backends-process

### ISSUE THREAD

**Issue by bruderj15** [tweag/smtlib-backends#72]
Hello all.

**Is your feature request related to a problem? Please describe.**
I am glad that with `v0.4@smtlib-backends` you have removed the default production of models as discussed in #70 .
When using `smtlib-backends-process` as well in the same project we unfortunately are forced to use `v0.3@smtlib-backends`.

**Describe the solution you'd like**
Update the upper bound of `smtlib-backends` to `0.4` in `smtlib-backends-process`.

**Comment by facundominguez** [comment]
Thanks @bruderj15. I updated the bounds in hackage revisions and updated the bounds in the repo in #73.
